name: Coverage

on:
  workflow_dispatch:
  pull_request:
    paths: ["contracts/**", "test/**"]
    types: [opened, review_requested]
  push:
    branches: [main]

jobs:
  coverage:
    runs-on: "ubuntu-latest"
    timeout-minutes: 15
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: "Install the dependencies"
        run: "npm install"

      - name: "Run coverage"
        run: "yarn coverage:ci"

      - name: "Add coverage summary"
        run: |
          echo "## coverage results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
