name: Static Analysis
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "contracts/**"
      - ".github/workflows/slither.yaml"
  pull_request:
    branches: [main, development]
    paths:
      - "contracts/**"
      - ".github/workflows/slither.yaml"

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile
        run: "npx hardhat compile --force"

      - name: Run Slither
        uses: crytic/slither-action@v0.3.0
        id: slither
        with:
          node-version: 16
          sarif: results.sarif
          fail-on: none
          ignore-compile: true

      # - name: Upload SARIF file
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: ${{ steps.slither.outputs.sarif }}
